version: '3.8'

services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy.rust
    ports:
      - "127.0.0.1:1080:1080"
    command: "--host 0.0.0.0 --port 1080"

  encrypt:
    build:
      context: .
      dockerfile: Dockerfile.encrypt
    command: "chacha20"
    environment:
      - CHACHA20_KEY="123456789012345678901234567890"
    
  decrypt:
    build:
      context: .
      dockerfile: Dockerfile.decrypt
    command: "chacha20"
    environment:
      - CHACHA20_KEY="123456789012345678901234567890"

  firewall:
    build:
      context: .
      dockerfile: Dockerfile.firewall
    command: "--host 0.0.0.0"

  netcat:
      image: busybox
      command: "nc -l -p 12345"
      ports:
        - "127.0.0.1:12345:12345"
      restart: always