version: '3.8'

services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy.rust
    ports:
      - "127.0.0.1:1080:1080"
    command: "--host 0.0.0.0 --port 1080 --chain socks6://encrypt:1080 --chain socks6://decrypt:1080 --chain socks6://firewall:1080"
    networks:
      net:
        ipv4_address: 172.16.238.2 

  encrypt:
    build:
      context: .
      dockerfile: Dockerfile.encrypt
    command: "chacha20"
    environment:
      - CHACHA20_KEY="123456789012345678901234567890"
    networks:
      net:
        ipv4_address: 172.16.238.3
      
  decrypt:
    build:
      context: .
      dockerfile: Dockerfile.decrypt
    command: "chacha20"
    environment:
      - CHACHA20_KEY="123456789012345678901234567890"
    networks:
      net:
        ipv4_address: 172.16.238.4   

  firewall:
    build:
      context: .
      dockerfile: Dockerfile.firewall
    command: "--host 0.0.0.0"
    networks:
      net:
        ipv4_address: 172.16.238.5           


  netcat:
      image: busybox
      command: "nc -l -p 12345"
      restart: always
      networks:
        net:
          ipv4_address: 172.16.238.6     

networks:
    net:
        ipam:
            driver: default
            config:
                - subnet: "172.16.238.0/24"