apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: firewall
  name: firewall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firewall
  strategy: {}
  template:
    metadata:
      labels:
        app: firewall
    spec:
      containers:
        - image: anmolbh/bfc_firewall
          name: firewall
          ports:
            - containerPort: 1080
          args: ["--host", "0.0.0.0"]
      restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: firewall
spec:
  type: NodePort
  selector:
    app: firewall
  ports:
    - port: 1080
      targetPort: 1080
      nodePort: 30021
      protocol: TCP