apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: proxy
  name: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  strategy: {}
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - image: anmolbh/bfc_proxy_rust
          name: proxy
          ports:
            - containerPort: 1080
          args: ["--host", "0.0.0.0", "--port", "1080", "--chain", "socks6://encrypt:1080", "--chain", "socks6://decrypt:1080", "--chain", "socks6://firewall:1080"]
      restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: proxy
  name: proxy
spec:
  type: NodePort
  selector:
    app: proxy
  ports:
    - port: 1080
      targetPort: 1080
      nodePort: 30007
      protocol: TCP
